services:
  selenium-hub:
    image: selenium/hub:4.22.0
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.22.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    shm_size: "2g"
    deploy:
      replicas: 5   # 5 Chrome nodes

  firefox:
    image: selenium/node-firefox:4.22.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    shm_size: "2g"
    deploy:
      replicas: 5   # 5 Firefox nodes
